# Generated by Django 4.0.4 on 2022-06-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_contacto_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='id',
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombre',
            field=models.TextField(max_length=10, primary_key=True, serialize=False, verbose_name='Nombre de usuario'),
        ),
    ]
